const bios = {
    einstein: `I am a German-born theoretical physicist. I developed the theory of relativity, one of the two pillars of modern physics (alongside quantum mechanics). My work is also known for its influence on the philosophy of science itself. I am perhaps best known in popular culture for my mass:energy equivalence formula E = mc^2 (which has been dubbed "the world's most famous equation"). I received the 1921 Nobel Prize in Physics "for services to theoretical physics, and especially for discovery of the law of the photoelectric effect", a pivotal step in the evolution of quantum theory.`,
    turing: `I am an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. I was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer. People widely regard me to be the father of theoretical computer science and artificial intelligence. During the Second World War, I also worked for the Government Code and Cypher School (GC&CS) at Bletchley Park, Britain's codebreaking centre. There I devised a number of techniques for speeding the breaking of German ciphers which played a pivotal role in cracking intercepted coded messages that enabled the Allies to defeat the Nazis in many crucial engagements, including the Battle of the Atlantic, in so doing helping to win the war.`,
    franklin: `I am an English chemist and X-ray crystallographer who made contributions to the understanding of the molecular structures of DNA (deoxyribonucleic acid), RNA (ribonucleic acid), viruses, coal, and graphite. Although my works on coal and viruses were recognized in my field, my pivotal contributions to the discovery of the double-helix structure of DNA were largely overlooked at the time.`,
    wilczek: `I am an American theoretical physicist, mathematician and a Nobel laureate. Currently, I am the Herman Feshbach Professor of Physics at the Massachusetts Institute of Technology (MIT), full Professor at Stockholm University, as well as a Distinguished Origins Professor at Arizona State University.`,
    maxwell: `I am a Scottish scientist in the field of mathematical physics. My most notable achievement was to formulate the classical theory of electromagnetic radiation, bringing together for the first time electricity, magnetism, and light as manifestations of the same phenomenon. My work, known as "Maxwell's equations" for electromagnetism have been called the "second great unification in physics" after the first one realised by Isaac Newton. With the publication of "A Dynamical Theory of the Electromagnetic Field" in 1865, I demonstrated that electric and magnetic fields travel through space as waves moving at the speed of light.`,
    noether: `I am a German mathematician known for making landmark contributions to abstract algebra and theoretical physics. I have been described by Pavel Alexandrov, Albert Einstein, Jean DieudonnÃ©, Hermann Weyl, and Norbert Wiener as the most important woman in the history of mathematics. As one of the leading mathematicians of my time, I developed the theories of rings, fields, and algebras. In physics, my work known as "Noether's theorem" explains the connection between symmetry and conservation laws.`,
};

export default bios;
